[tool.poetry]
<<<<<<< HEAD
name = "academy-future"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.8"
=======
name = "academy-future3"
version = "0.1.0"
description = ""
authors = ["lucasbragasilva <lucasbragadasilva@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
>>>>>>> 3dc3247 (estudo_ciencias_dados)

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
